//script generated by SiteXpert (www.xtreeme.com)
//Copyright(C) 1998-2003 Xtreeme GmbH
var ver='4.0.3'
var m1=new Object
m1.name='m1'
m1.fnm='menu_m1'
if(!window.lastm||window.lastm<1)lastm=1
m1.v17=null
m1.v17Timeout=''
var maxZ=1000
m1.v18
m1.targetFrame
var docLoaded=false
m1.bIncBorder=true
m1.v29=null
m1.v29Str=''
m1.v55=50
m1.scrollStep=10
m1.fadingSteps=8
m1.itemOverDelay=0
m1.transTLO=0
m1.fixSB=0
m1.v62=1
m1.v21="."
m1.maxlev=1
m1.v22=0
m1.sepH=10
m1.bHlNL=1
m1.showA=1
m1.bVarWidth=0
m1.bShowDel=0
m1.scrDel=0
m1.v23=90
m1.levelOffset=20
m1.bord=1
m1.vertSpace=2
m1.sep=0
m1.v19=false
m1.bkv=0
m1.rev=0
m1.shs=0
m1.xOff=0
m1.yOff=0
m1.xSOff=0
m1.ySOff=0
m1.v20=false
m1.cntFrame=""
m1.menuFrame=""
m1.v24=""
m1.mout=true
m1.iconSize=8
m1.closeDelay=1000
m1.tlmOrigBg="#FF8000"
m1.tlmOrigCol="White"
m1.v25=false
m1.v52=false
m1.v60=0
m1.v11=false
m1.v10=0
m1.ppLeftPad=5
m1.v54=0
m1.v01=2
m1.tlmHlBg="#FFB66C"
m1.tlmHlCol="Gray"
m1.borderCol="#B0B0B0"
m1.menuHorizontal=false
m1.scrollHeight=6
m1.attr=new Array("12px",false,false,"White","#FF8F20","#FF8F20","Georgia,Times New Roman,Times,serif","Gray","White","#FF8000")
m1mn1=new Array
(
"Media Kit","MediaKit/index.html",0,"",""
)
absPath=""
if(m1.v19&&!m1.v20){
if(window.location.href.lastIndexOf("\\")>window.location.href.lastIndexOf("index.html")) {sepCh = "\\" ;} else {sepCh = "index.html" ;}
absPath=window.location.href.substring(0,window.location.href.lastIndexOf(sepCh)+1)}
m1.v02=m1.v23
document.write("<style type='text/css'>\n.m1CL0,.m1CL0:link{text-decoration:none;width:100%;color:White; }\n.m1CL0:visited{color:White}\n.m1mit{padding-left:5px;padding-right:15px;color:White; font-family:Georgia,Times New Roman,Times,serif; font-size:15px; }\n"+"</"+"style>")
document.write("<script type='text/javascript' src='menu_dom.js'></"+"script>")
